apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/uthami-rasu/gitops.git
        revision: main
        directories:
          - path: environments/dev/* # 🔒 ONLY DEV

  template:
    metadata:
      name: "dev-{{path.basename}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/uthami-rasu/gitops.git
        targetRevision: main
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app-dev # ✅ your namespace

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
