apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: portal
          # - name: orders # placeholder for future services
  template:
    metadata:
      name: "dev-{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/uthami-rasu/gitops.git
        targetRevision: main
        path: charts/{{name}}
        helm:
          valueFiles:
            - ../../environments/dev/{{name}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app-dev-1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
