apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: demo-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: therazz28/demo-app:v0.1 # 🔁 replace with your image
          ports:
            - containerPort: 80
